### ISSUE TITLE
noiseKeyPair undefined

### ISSUE THREAD

**Issue by estebanprimost** [andrewosh/hypercore-promisifier#1]
Hi @andrewosh, nice work with this library 👍🏻

Issue: After wrapping the feed with `hypercore-promisifier` it returns undefined for `noiseKeyPair`. This is my test:
```javascript
const assert = require('assert')
const hypercore = require('hypercore')
const { toPromises } = require('hypercore-promisifier')

const feed = hypercore('./data')

feed.ready(() => {
  assert(feed.noiseKeyPair, 'hypercore: noiseKeyPair undefined')
  
  const wrapper = toPromises(feed)
  assert(wrapper.noiseKeyPair, 'hypercore-promisifier: noiseKeyPair undefined')
})
```
Versions:
- "hypercore": "^9.7.0"
- "hypercore-promisifier": "^1.0.3"

Thanks!

**Comment by andrewosh** [comment]
Hey @estebanprimost, thanks for the issue.

hypercore-promisier will probably never re-export the complete API surface of Hypercore -- only the most critical parts of the public API. It's just a lot to keep track of, and especially the undocumented-but-public ones are subject to change.

Given that, I added an `unwrap` function to v1.1.0. For things like properties (that don't depend on async behavior), you can now do something like:
```js
const hypercore = require('hypercore')
const ram = require('random-access-memory')
const { toPromises, unwrap } = require('hypercore-promisifier')

const core = hypercore(ram)
const wrapper = toPromises(core)
// Get the noiseKeypair
unwrap(wrapper).noiseKeyPair

// Can also be called on the normal Hypercore.
unwrap(wrapper).noiseKeyPair === unwrap(core).noiseKeyPair
```

Think this will work for you?

**Comment by estebanprimost** [comment]
Thanks @andrewosh, it works now. We are using it from an `hyperbee` instance, so we need to unwrap our `db.feed` now.

**Comment by andrewosh** [comment]
Ah that's actually an interesting point. It simplifies Hyperbee internals to have db.feed be a promisified Hypercore, but re-exporting that as a public property means that perhaps hypercore-promisifier does need all public properties after all, without `unwrap`.

If we're going with the unwrap approach, then Hyperbee should have a getter like:
```js
class Hyperbee {
  constructor (feed) {
    this._feed = toPromises(feed)
  }
  ...
  get feed () {
     return unwrap(this._feed)
  }
}
```

Thanks for bringing this up -- hadn't considered it.

**Comment by estebanprimost** [comment]
Yes, that _unwrapped_ feed getter will be great. Thanks again!.
